# Generated by Django 4.2.4 on 2023-08-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='articles_tags', to='articles.tag'),
        ),
    ]
